In [1]:
import pandas as pd 


data = pd.read_csv("UL_PRB_data_set.csv")
unseen = pd.read_csv("selected_cells_unseen.csv")

data.head()

,Short name,Date,N.PRB.UL.DrbUsed.Avg[%],N.ThpVol.UL,N.User.RRCConn.Active.UL.Avg
0,cell000,2025-01-20 00:00:00,0.178846,6173.480,0.052
1,cell000,2025-01-20 00:15:00,0.096154,2877.464,0.018
2,cell000,2025-01-20 00:30:00,0.075000,3541.224,0.021
3,cell000,2025-01-20 00:45:00,0.148077,9373.480,0.033
4,cell000,2025-01-20 01:00:00,0.563462,39179.448,0.124

In [2]:
unseen.head()

,Short name,Date,N.PRB.UL.DrbUsed.Avg[%],N.ThpVol.UL,N.User.RRCConn.Active.UL.Avg
0,cell230,2025-02-14 00:00:00,0.315385,16190.448,0.081
1,cell230,2025-02-14 00:15:00,0.001923,11.552,0.000
2,cell230,2025-02-14 00:30:00,0.000000,0.040,0.000
3,cell230,2025-02-14 00:45:00,0.003846,103.104,0.002
4,cell230,2025-02-14 01:00:00,0.000000,0.120,0.000