In [ ]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

df = pd.read_csv("UL_PRB_data_set.csv")

In [4]:
df.head()

,Short name,Date,N.PRB.UL.DrbUsed.Avg[%],N.ThpVol.UL,N.User.RRCConn.Active.UL.Avg
0,cell000,2025-01-20 00:00:00,0.178846,6173.480,0.052
1,cell000,2025-01-20 00:15:00,0.096154,2877.464,0.018
2,cell000,2025-01-20 00:30:00,0.075000,3541.224,0.021
3,cell000,2025-01-20 00:45:00,0.148077,9373.480,0.033
4,cell000,2025-01-20 01:00:00,0.563462,39179.448,0.124

In [13]:

def dataframe_summary(df: pd.DataFrame) -> pd.DataFrame:
    summary = []

    for col in df.columns:
        col_data = df[col]

        unique_values = col_data.dropna().unique()
        unique_count = len(unique_values)

        summary.append({
            "column": col,
            "unique_count": unique_count,
            "missing_values": col_data.isna().sum(),
            "non_nan_values": col_data.notna().sum(),
            "sample_values": unique_values.tolist()
        })

    result = pd.DataFrame(summary)

    # sort by unique value count descending
    result = result.sort_values(by="unique_count", ascending=False).reset_index(drop=True)

    return result


# usage:
summary_df = dataframe_summary(df)
summary_df

,column,unique_count,missing_values,non_nan_values,sample_values
0,N.ThpVol.UL,783979,0,1301760,"[6173.48, 2877.464, 3541.224, 9373.48, 39179.4..."
1,N.PRB.UL.DrbUsed.Avg[%],59159,0,1301760,"[0.1788461538461538, 0.0961538461538461, 0.075..."
2,N.User.RRCConn.Active.UL.Avg,6342,0,1301760,"[0.052, 0.018, 0.021, 0.033, 0.124, 0.074, 0.0..."
3,Date,5760,0,1301760,"[2025-01-20 00:00:00, 2025-01-20 00:15:00, 202..."
4,Short name,226,0,1301760,"[cell000, cell001, cell002, cell003, cell004, ..."

In [10]:
df["Short name"].unique().tolist()

['cell000',
 'cell001',
 'cell002',
 'cell003',
 'cell004',
 'cell005',
 'cell006',
 'cell007',
 'cell008',
 'cell009',
 'cell010',
 'cell011',
 'cell012',
 'cell013',
 'cell014',
 'cell015',
 'cell016',
 'cell017',
 'cell018',
 'cell019',
 'cell020',
 'cell021',
 'cell022',
 'cell023',
 'cell024',
 'cell025',
 'cell026',
 'cell027',
 'cell028',
 'cell029',
 'cell030',
 'cell031',
 'cell032',
 'cell033',
 'cell034',
 'cell035',
 'cell036',
 'cell037',
 'cell038',
 'cell039',
 'cell040',
 'cell041',
 'cell042',
 'cell043',
 'cell044',
 'cell045',
 'cell046',
 'cell047',
 'cell048',
 'cell049',
 'cell050',
 'cell051',
 'cell052',
 'cell053',
 'cell054',
 'cell055',
 'cell056',
 'cell057',
 'cell058',
 'cell059',
 'cell060',
 'cell061',
 'cell062',
 'cell063',
 'cell064',
 'cell065',
 'cell066',
 'cell067',
 'cell068',
 'cell069',
 'cell070',
 'cell071',
 'cell072',
 'cell073',
 'cell074',
 'cell075',
 'cell076',
 'cell077',
 'cell078',
 'cell079',
 'cell080',
 'cell081',
 'cell082',
 'cell083',
 'cell084',
 'cell085',
 'cell086',
 'cell087',
 'cell088',
 'cell089',
 'cell090',
 'cell091',
 'cell092',
 'cell093',
 'cell094',
 'cell095',
 'cell096',
 'cell097',
 'cell098',
 'cell099',
 'cell100',
 'cell101',
 'cell102',
 'cell103',
 'cell104',
 'cell105',
 'cell106',
 'cell107',
 'cell108',
 'cell109',
 'cell110',
 'cell111',
 'cell112',
 'cell113',
 'cell114',
 'cell115',
 'cell116',
 'cell117',
 'cell118',
 'cell119',
 'cell120',
 'cell121',
 'cell122',
 'cell123',
 'cell124',
 'cell125',
 'cell126',
 'cell127',
 'cell128',
 'cell129',
 'cell130',
 'cell131',
 'cell132',
 'cell133',
 'cell134',
 'cell135',
 'cell136',
 'cell137',
 'cell138',
 'cell139',
 'cell140',
 'cell141',
 'cell142',
 'cell143',
 'cell144',
 'cell145',
 'cell146',
 'cell147',
 'cell148',
 'cell149',
 'cell150',
 'cell151',
 'cell152',
 'cell153',
 'cell154',
 'cell155',
 'cell156',
 'cell157',
 'cell158',
 'cell159',
 'cell160',
 'cell161',
 'cell162',
 'cell163',
 'cell164',
 'cell165',
 'cell166',
 'cell167',
 'cell168',
 'cell169',
 'cell170',
 'cell171',
 'cell172',
 'cell173',
 'cell174',
 'cell175',
 'cell176',
 'cell177',
 'cell178',
 'cell179',
 'cell180',
 'cell181',
 'cell182',
 'cell183',
 'cell184',
 'cell185',
 'cell186',
 'cell187',
 'cell188',
 'cell189',
 'cell190',
 'cell191',
 'cell192',
 'cell193',
 'cell194',
 'cell195',
 'cell196',
 'cell197',
 'cell198',
 'cell199',
 'cell200',
 'cell201',
 'cell202',
 'cell203',
 'cell204',
 'cell205',
 'cell206',
 'cell207',
 'cell208',
 'cell209',
 'cell210',
 'cell211',
 'cell212',
 'cell213',
 'cell214',
 'cell215',
 'cell216',
 'cell217',
 'cell218',
 'cell219',
 'cell220',
 'cell221',
 'cell222',
 'cell223',
 'cell224',
 'cell225']